<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HRDashboard</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="index.html" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="organization.html" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="css\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="images\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="js\dashboard.js" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="js\organization.js" CopyToOutputDirectory="PreserveNewest" />
    <Content Update="js\innodep_hr_dummy_200.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" />
  </ItemGroup>
</Project>
